---
- name: thisis used for testing the variables which are given from outside
  vars_files:
     - /home/vars1.yml
  hosts: all
  tasks:
   - name: this is used for installing different pkgs to install 
     yum:
      name: "{{ item }}"
      state: present
     with_items:
       - "{{ pkg }}"

