---
- name: this is used for installing mysql 
  hosts: 3.89.124.146
  become: true
  become_user: root
  vars:
   mysql: 
    - mysql-community-client-5.7.30-1.el7.x86_64.rpm
    - mysql-community-common-5.7.30-1.el7.x86_64.rpm
    - mysql-community-devel-5.7.30-1.el7.x86_64.rpm
    - mysql-community-embedded-5.7.30-1.el7.x86_64.rpm
    - mysql-community-embedded-compat-5.7.30-1.el7.x86_64.rpm
    - mysql-community-embedded-devel-5.7.30-1.el7.x86_64.rpm
    - mysql-community-libs-compat-5.7.30-1.el7.x86_64.rpm
    - mysql-community-libs-5.7.30-1.el7.x86_64.rpm
    - mysql-community-server-5.7.30-1.el7.x86_64.rpm
    - mysql-community-test-5.7.30-1.el7.x86_64.rpm
  tasks:
   - name: this is used for copying the tar files from controller to remote hosts
     copy: 
      src: /home/mysql-5.7.30-1.el7.x86_64.rpm-bundle.tar
      dest: /home/
   - name: this is used for unarchiving the bundle file
     unarchive:
      src: /home/mysql-5.7.30-1.el7.x86_64.rpm-bundle.tar
      dest: /home/
   - name: this is for installing the mysql rpm
     yum:
      name: "/home/{{ item }}"
      state: present
     with_items:
       - "{{ mysql }}"
...
