---
- name: this is used for testing the groups the hosts
  hosts: "{{groups['test']}}"
  gather_facts: true
  become: true
  become_user: root
  tasks:
   - name: this is for creating a  file
     file:
      name: /tmp/dir1
      state: directory
   - name: this is for printing the output
     command: ls -lrth
     register: list
   - debug:
      #msg: this is installed on {{inventory_hostname}}which is {{ansible_hostname}}
      var: list.stdout_lines
...
