---
- name: this is for testing the debug and capture th password for mysql
  hosts: all
  become: true
  become_user: root
  gather_facts: yes
  tasks:
   - name: this is for showing the password file
     shell:  awk  '/ A temporary password is generated for/{print $NF}' /var/log/mysqld.log
     register: passwd
   - name: this for capturing the password in password file
     debug:
      msg: "this is {{ passwd.stdout_lines }}"
   - name: this is copying the lines in to another file
     copy:
      content: "{{ passwd.stdout_lines }}"
      dest: /var/www/html/index.html
      
  
